import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const COLORS = {
  primary: "#1a1a1a",
  secondary: "#666666",
  accent: "#22c55e",
  border: "#000000",
  lightBg: "#f9fafb",
};

/**
 * Common header for all reports
 */
const addHeader = (doc, data, title) => {
  const pageWidth = doc.internal.pageSize.width;

  // Store Name
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.primary);
  doc.text(data.storeName || "RM TOYS", 20, 20);

  // Address & Contacts
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COLORS.secondary);
  doc.text(data.storeAddress || "", 20, 26);
  doc.text(`${data.storePhone} | ${data.storeEmail}`, 20, 31);

  // Report Title & Meta
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.accent);
  doc.text(title, pageWidth - 20, 20, { align: "right" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COLORS.secondary);
  doc.text(`Generated: ${data.generatedAt}`, pageWidth - 20, 26, {
    align: "right",
  });
  if (data.dateRange) {
    doc.setFillColor(243, 244, 246);
    doc.rect(pageWidth - 70, 30, 50, 6, "F");
    doc.setFont("courier", "normal");
    doc.setFontSize(9);
    doc.text(data.dateRange, pageWidth - 45, 34, { align: "center" });
  }

  // Divider Line
  doc.setDrawColor(0);
  doc.setLineWidth(1);
  doc.line(20, 40, pageWidth - 20, 40);
};

/**
 * Add summary cards
 */
const addSummaryCards = (doc, cards, startY) => {
  const pageWidth = doc.internal.pageSize.width;
  const margin = 20;
  const gap = 10;
  const totalGaps = (cards.length - 1) * gap;
  const availableWidth = pageWidth - (margin * 2) - totalGaps;
  const cardWidth = availableWidth / cards.length;
  const cardHeight = 25;
  let currentX = margin;

  cards.forEach((card) => {
    // Card Box
    doc.setDrawColor(COLORS.border);
    doc.setFillColor(249, 250, 251);
    doc.rect(currentX, startY, cardWidth, cardHeight, "FD");

    // Title
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(COLORS.secondary);
    doc.text(card.title.toUpperCase(), currentX + cardWidth / 2, startY + 8, {
      align: "center",
    });

    // Value
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(
      card.highlight ? COLORS.accent : COLORS.primary
    );
    doc.text(card.value.toString(), currentX + cardWidth / 2, startY + 18, {
      align: "center",
    });

    currentX += cardWidth + gap;
  });
};

/**
 * Add footer
 */
const addFooter = (doc, data) => {
  const pageHeight = doc.internal.pageSize.height;
  doc.setDrawColor(200);
  doc.setLineWidth(0.5);
  doc.setLineDash([2, 2], 0);
  doc.line(20, pageHeight - 20, doc.internal.pageSize.width - 20, pageHeight - 20);

  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text(
    "This is a computer-generated report. No signature required.",
    doc.internal.pageSize.width / 2,
    pageHeight - 15,
    { align: "center" }
  );
  doc.text(
    `Generated by ${data.storeName} Admin Dashboard`,
    doc.internal.pageSize.width / 2,
    pageHeight - 10,
    { align: "center" }
  );
};

// -------------------------------------------------------------
// EXPORT FUNCTIONS
// -------------------------------------------------------------

export const generateSalesPDF = (data) => {
  const doc = new jsPDF();

  addHeader(doc, data, "SALES REPORT");

  // Summary Cards
  const cards = [
    {
      title: "Total Revenue",
      value: `P${data.totalRevenue.toLocaleString()}`,
      highlight: true,
    },
    { title: "Total Orders", value: data.totalOrders },
    {
      title: "Avg. Order Value",
      value: `P${data.avgOrderValue.toFixed(2)}`,
    },
  ];
  addSummaryCards(doc, cards, 50);

  // Table
  autoTable(doc, {
    startY: 85,
    head: [["Period", "Orders", "Revenue"]],
    body: data.salesData.map((item) => [
      item.period,
      item.orderCount,
      `P${item.totalSales.toLocaleString()}`,
    ]),
    theme: "grid",
    headStyles: { fillColor: COLORS.primary, textColor: 255 },
    columnStyles: {
      0: { fontStyle: "bold" },
      2: { error: "right", halign: "right" },
    },
  });

  addFooter(doc, data);
  doc.save(`Sales-Report-${new Date().toISOString().split("T")[0]}.pdf`);
};

export const generateOrdersPDF = (data) => {
  const doc = new jsPDF();

  addHeader(doc, data, "ORDERS REPORT");

  // Summary Cards
  const cards = [
    { title: "Pending", value: data.pendingCount },
    { title: "Processing", value: data.processingCount },
    { title: "Delivered", value: data.deliveredCount, highlight: true },
    { title: "Cancelled", value: data.cancelledCount },
  ];
  addSummaryCards(doc, cards, 50);

  // Table
  autoTable(doc, {
    startY: 85,
    head: [["Order ID", "Customer", "Date", "Status", "Total"]],
    body: data.recentOrders.map((order) => [
      order.orderId,
      order.customerName,
      new Date(order.createdAt).toLocaleDateString(),
      order.status,
      `P${order.totalPrice.toLocaleString()}`,
    ]),
    theme: "grid",
    headStyles: { fillColor: COLORS.primary, textColor: 255 },
    columnStyles: {
      4: { halign: "right" },
    },
  });

  addFooter(doc, data);
  doc.save(`Orders-Report-${new Date().toISOString().split("T")[0]}.pdf`);
};

export const generateInventoryPDF = (data) => {
  const doc = new jsPDF();

  addHeader(doc, data, "INVENTORY REPORT");

  // Summary Cards
  const cards = [
    { title: "Total Products", value: data.totalProducts },
    { title: "Low Stock", value: data.lowStockCount, highlight: true },
    { title: "Out of Stock", value: data.outOfStockCount },
  ];
  addSummaryCards(doc, cards, 50);

  // Table
  autoTable(doc, {
    startY: 85,
    head: [["Product", "Category", "Price", "Stock", "Status"]],
    body: data.products.map((p) => [
      p.productName,
      p.category,
      `P${p.price.toLocaleString()}`,
      p.stock,
      p.stockStatus,
    ]),
    theme: "grid",
    headStyles: { fillColor: COLORS.primary, textColor: 255 },
    styles: { fontSize: 8 },
    columnStyles: {
      2: { halign: "right" },
      3: { halign: "center" },
    },
    didParseCell: function (data) {
      if (data.section === "body" && data.column.index === 4) {
        if (data.cell.raw === "Out of Stock") {
            data.cell.styles.textColor = [220, 38, 38]; // Red
        } else if (data.cell.raw === "Low Stock") {
            data.cell.styles.textColor = [217, 119, 6]; // Orange/Amber
        } else {
            data.cell.styles.textColor = [22, 163, 74]; // Green
        }
      }
    },
  });

  addFooter(doc, data);
  doc.save(`Inventory-Report-${new Date().toISOString().split("T")[0]}.pdf`);
};

export const generateInvoicePDF = (data) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // --- HEADER: STORE INFO ---
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.primary);
  doc.text(data.storeName, 20, 20);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COLORS.secondary);
  doc.text(data.storeAddress, 20, 26);
  doc.text(`${data.storePhone} | ${data.storeEmail}`, 20, 31);

  // --- INVOICE TITLE & META ---
  doc.setFontSize(26);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.accent); // Brand color for INVOICE
  doc.text("INVOICE", pageWidth - 20, 25, { align: "right" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COLORS.secondary);
  doc.text(`Order ID: ${data.orderId}`, pageWidth - 20, 32, { align: "right" });
  doc.text(`Date: ${data.orderDate}`, pageWidth - 20, 37, { align: "right" });

  // Divider
  doc.setDrawColor(200);
  doc.line(20, 45, pageWidth - 20, 45);

  // --- CUSTOMER & SHIPPING INFO ---
  const leftColX = 20;
  const rightColX = pageWidth / 2 + 10;
  const sectionY = 55;

  // Bill To
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.primary);
  doc.text("BILL TO:", leftColX, sectionY);
  
  doc.setFont("helvetica", "normal");
  doc.setTextColor(COLORS.secondary);
  doc.text(data.customerName, leftColX, sectionY + 6);
  doc.text(data.customerEmail, leftColX, sectionY + 11);
  doc.text(data.customerPhone, leftColX, sectionY + 16);

  // Ship To (Address)
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.primary);
  doc.text("SHIP TO:", rightColX, sectionY);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(COLORS.secondary);
  // Split long addresses
  const addressLines = doc.splitTextToSize(data.shippingAddress, pageWidth / 2 - 30);
  doc.text(addressLines, rightColX, sectionY + 6);

  // --- PAYMENT STATUS BADGE ---
  const badgeY = sectionY + 30;
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.primary);
  doc.text("PAYMENT METHOD:", leftColX, badgeY);
  doc.setFont("helvetica", "normal");
  doc.text(data.paymentMethod, leftColX, badgeY + 6);

  // Status Box
  const statusColor = data.paymentStatus === "Paid" ? [34, 197, 94] : [239, 68, 68]; // Green or Red
  doc.setFillColor(...statusColor);
  doc.roundedRect(rightColX, badgeY - 2, 40, 10, 2, 2, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text(data.paymentStatus.toUpperCase(), rightColX + 20, badgeY + 4, { align: "center" });

  // --- ORDER ITEMS TABLE ---
  autoTable(doc, {
    startY: badgeY + 20,
    head: [["Item Description", "Category", "Qty", "Unit Price", "Total"]],
    body: data.orderItems.map((item) => [
      item.productName,
      item.category,
      item.quantity,
      `P${item.unitPrice.toLocaleString('en-US', {minimumFractionDigits: 2})}`,
      `P${item.totalPrice.toLocaleString('en-US', {minimumFractionDigits: 2})}`,
    ]),
    theme: "striped",
    headStyles: { 
      fillColor: COLORS.primary, 
      textColor: 255,
      fontStyle: "bold" 
    },
    columnStyles: {
      0: { cellWidth: 70 }, // Description
      2: { halign: "center" }, // Qty
      3: { halign: "right" }, // Price
      4: { halign: "right", fontStyle: "bold" }, // Total
    },
  });

  // --- TOTALS SECTION ---
  let finalY = doc.lastAutoTable.finalY + 10;
  const totalsX = pageWidth - 70;
  const valueX = pageWidth - 20;
  const step = 7;

  // Helper for totals row
  const addTotalRow = (label, value, isBold = false) => {
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    doc.setTextColor(COLORS.primary);
    doc.setFontSize(10);
    doc.text(label, totalsX, finalY);
    doc.text(value, valueX, finalY, { align: "right" });
    finalY += step;
  };

  addTotalRow("Subtotal:", `P${data.subtotal.toLocaleString('en-US', {minimumFractionDigits: 2})}`);
  addTotalRow("Shipping:", `P${data.shippingPrice.toLocaleString('en-US', {minimumFractionDigits: 2})}`);
  
  if (data.vatAmount > 0) {
    addTotalRow("VAT (12%):", `P${data.vatAmount.toLocaleString('en-US', {minimumFractionDigits: 2})}`);
  }
  
  if (data.usedCredits > 0) {
    doc.setTextColor(239, 68, 68); // Red for discount
    addTotalRow("Credits Used:", `-P${data.usedCredits.toLocaleString('en-US', {minimumFractionDigits: 2})}`);
    doc.setTextColor(COLORS.primary); // Reset
  }

  // Grand Total Line
  doc.setDrawColor(200);
  doc.line(totalsX - 10, finalY - 4, pageWidth - 20, finalY - 4);
  finalY += 2;

  // Grand Total
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(COLORS.accent);
  doc.text("TOTAL:", totalsX, finalY + 2);
  doc.text(`P${data.totalPrice.toLocaleString('en-US', {minimumFractionDigits: 2})}`, valueX, finalY + 2, { align: "right" });

  // --- FOOTER ---
  const pageHeight = doc.internal.pageSize.height;
  doc.setDrawColor(200);
  doc.setLineWidth(0.5);
  doc.setLineDash([2, 2], 0);
  doc.line(20, pageHeight - 20, pageWidth - 20, pageHeight - 20);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(156, 163, 175);
  doc.text(
    "Thank you for your business!",
    pageWidth / 2,
    pageHeight - 15,
    { align: "center" }
  );
  doc.text(
    `Order ID: ${data.orderId} | Generated by ${data.storeName}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: "center" }
  );

  doc.save(`Invoice-${data.orderId.slice(-8)}.pdf`);
};
