// utils/profanityFilter.js
export const PROFANITY_LIST = [
  // ===== ENGLISH ===== //
  "fuck",
  "shit",
  "asshole",
  "bitch",
  "bastard",
  "cunt",
  "pussy",
  "dick",
  "whore",
  "slut",
  "damn",
  "hell",
  "crap",
  "retard",
  "cock",
  "twat",
  "motherfucker",
  "son of a bitch",
  "douche",
  "douchebag",
  "jackass",
  "prick",
  "dipshit",
  "nutsack",
  "bollocks",
  "bloody",
  "arsehole",

  // English Leetspeak/Misspellings
  "fck",
  "fuk",
  "f*ck",
  "f**k",
  "f***",
  "f@ck",
  "phuck",
  "sh1t",
  "sh!t",
  "sht",
  "shyt",
  "s#it",
  "b1tch",
  "b!tch",
  "bi7ch",
  "bitsh",
  "b*tch",
  "azzhole",
  "a$$hole",
  "4sshole",
  "a55hole",
  "c0ck",
  "d1ck",
  "d!ck",
  "d*ck",
  "diq",
  "dicc",
  "dik",
  "pu$$y",
  "p@ssy",
  "pussee",
  "pussi",
  "p*ssy",
  "wh0re",
  "h0e",
  "sl*t",
  "s1ut",
  "s|ut",
  "cr@p",
  "ret@rd",
  "r3tard",
  "tw@t",
  "d@mn",
  "damm",
  "mfkr",

  // ===== TAGALOG ===== //
  "putang ina",
  "putangina",
  "puta",
  "gago",
  "tang ina",
  "tangina",
  "bobo",
  "ulol",
  "lintik",
  "punyeta",
  "leche",
  "burat",
  "tarantado",
  "pokpok",
  "kantot",
  "iyot",
  "puke",
  "titi",
  "tite",
  "pekpek",
  "pepe",
  "bulbol",
  "bayag",
  "tungaw",
  "hinayupak",
  "hayop",
  "animal",
  "peste",
  "demonyo",
  "kamote",
  "sira ulo",
  "siraulo",
  "tanginamo",
  "yawa",
  "bwisit",
  "kupal",
  "kup@l",
  "kup4l",
  "gagi ka ba",
  "gagi",
  "bungol",
  "bungal",
  "epep",
  "pota",
  "gago",
  "tanga",

  // Tagalog Misspellings/Leetspeak
  "put@ng ina",
  "put@ngina",
  "p*tang ina",
  "puta#ina",
  "g@go",
  "p3p3",
  "t@ng ina",
  "b0b0",
  "b@b0",
  "ul*l",
  "u10l",
  "p*nyeta",
  "puny3ta",
  "p0k0k",
  "pokp0k",
  "l3che",
  "b*r@t",
  "bur@t",
  "bur4t",
  "k@ntot",
  "iy*t",
  "iy0t",
  "p*ke",
  "puk3",
  "t*ti",
  "t1t1",
  "p*kp*k",
  "pekp3k",
  "bul8l",
  "b@yag",
  "hin@yupak",
  "dem0nyo",
  "bw1sit",
  "sir@ ulo",
  "sir@ulo",
  "t@nginamo",
  "yaw@",
  "y@wa",

  // ===== BISAYA / CEBUANO ===== //
  "yawa",
  "unggoy",
  "bogo",
  "buang",
  "giatay",
  "yati",
  "pisti",
  "palaaway",
  "kanding",
  "langgam",
  "sungog",
  "bayot",
  "sipyat",
  "pala-inom",
  "kabuang",
  "ulol",
  "way batasan",
  "sabaw",
  "pakshet",
  "pakyu",
  "pakyaw",
  "inyot",
  "inatay",
  "hinampak",
  "piskat",
  "bahu kag ilok",
  "bahu kag lubut",
  "bahu kag baba",
  "bahu kag bilat",
  "itum kag tai",
  "la kag ihi",
  "la kag laway",
  "utut nimo",
  "daku kag bilat",
  "daku kag bugan",
  "daku kag itlog",
  "bilat sa iyang ina",
  "puki nimo",
  "tinggil nimo",
  "iyut",
  "lulu nimo",
  "lusu nimo",
  "siga kag mata",
  "daku kag ilung",
  "daku kag nawng",
  "baga kag nawng",
  "yaya imong nawng",
  "nawng nimo ay, tanga ka",
  "danghag imong nawng",
  "wa kay kasingkasing",
  "itum kag kasingkasing",
  "wa kay atay",
  "baga kag atay",

  // Bisaya Misspellings/Leetspeak
  "y@wa",
  "yaw4",
  "b0g0",
  "bu@ng",
  "gi@tay",
  "p!sti",
  "p*sti",
  "w@y batasan",
  "b@yot",
  "b4yot",
  "s!pyat",
  "iny*t",
  "iny0t",

  // ===== ILOCANO ===== //
  "langgong ka",
  "duldog",
  "lukdit mo",
  "ukininam",
  "lastog",
  "arem",
  "uki",
  "buto",
  "yotninam",
  "nagbangsit ka",
  "mulengleng",
  "umadayu ka",
  "nagalas ka",
  "nagalas ugalim",
  "patayen ka",
  "bekkelen",
  "salsal",
  "inta ag yot",
  "sadot",
  "iyot",
  "shet",
  "tabbed",
  "ukis ti saba",

  // Ilocano Misspellings/Leetspeak
  "uk1nam",
  "ukin@nam",
  "agas@m",
  "awan kw3nta",
  "l1ntek",
  "bu@ng",

  // ===== KAPAMPANGAN ===== //
  "bolang",
  "murit",
  "bugok",
  "batingan mu ku",
  "lokung diyablos",
  "anakputa ka",
  "antac nang inda mo",
  "tacneydamo",
  "taneydamo",
  "neydamo",
  "damo",
  "mabitas ca sa dungos",
  "sacdapul",
  "dipan na ca ning alti",
  "mayalti na ca canyan",
  "mayalti na ca balat",
  "pisti",
];

export const THREAT_LIST = [
  // Tagalog/Filipino Violent Threats
  "patayin kita",
  "papatayin kita",
  "pat*yin kita",
  "patayin ka",
  "sasaksakin kita",
  "puputulan kita",
  "bugbugin kita",
  "susugurin kita",
  "lagot ka",
  "susuntukin kita",
  "barilin kita",
  "titirahin kita",
  "batukan kita",
  "suntukin kita",
  "g*g*ng kita",
  "ihagis kita",
  "patumbahin kita",
  "susuntok kita",
  "pupukpukin kita",
  "put*lan kita",

  // Bisaya/Cebuano Violent Threats
  "patyon tika",
  "pamatyon tika",
  "sugatan tika",
  "bunalon tika",
  "tukaon tika",
  "pat*y*n tika",
  "susukot tika",
  "sundangon tika",

  // Hiligaynon/Ilonggo Violent Threats
  "patyon ta ikaw",
  "pat*yon ta ikaw",
  "sakiton ta ikaw",
  "bagulbolon ta ikaw",
  "sugaton ta ikaw",

  // Waray Violent Threats
  "patayon ko ikaw",
  "pat*yon ko ikaw",
  "sundangon ko ikaw",
  "sugaton ko ikaw",

  // Chavacano Violent Threats
  "mato yo contigo",
  "bunal yo contigo",
  "pate yo contigo",
  "apuyo yo contigo",

  // English Violent Threats
  "i'll kill you",
  "i will kill you",
  "i'll stab you",
  "i will stab you",
  "i'll shoot you",
  "i will shoot you",
  "i'll beat you up",
  "i will beat you up",
  "i'll hurt you",
  "i will hurt you",
  "i'll punch you",
  "i will punch you",
  "i'll slap you",
  "i will slap you",
  "i'll destroy you",
  "i will destroy you",
  "i'll assault you",
  "i will assault you",
  "i'll throw you",
  "i will throw you",
  "i'll cut you off",
  "i will cut you off",
  "i'll end you",
  "i will end you",
  "i'll make you suffer",
  "i will make you suffer",
  "i'll wreck you",
  "i will wreck you",
  "i'll f you",
  "i will f you",
  "i'm going to kill you",
  "im gonna kill you",
  "i'm gonna stab you",
  "imma stab you",
  "imma hurt you",
  "imma beat you up",
  "i'm gonna beat you up",
  "i'm gonna hurt you",
  "i'm gonna punch you",
  "i'm gonna wreck you",
  "i'm gonna break you",
  "i'm gonna break your face",
  "i will break your bones",
  "i will break you",
  "i'll make you bleed",
  "you're dead",
  "you are dead",
  "you're f dead",
  "you're going to die",
  "you'll die for this",
  "i'm coming for you",
  "i'm coming to get you",
  "i'll end your life",
  "i'll ruin you",
  "i'll tear you apart",
  "i'll crush you",
  "i'll mutilate you",
  "i'll bash your head in",
  "i'll cave your head in",
  "i'll knock you out",
  "i'll burn you alive",
  "i'll drown you",
  "i'll shoot your face",
  "i'll stab your eyes",
  "i'll rip you apart",
  "i'll skin you",
  "i'll strangle you",
  "i'll choke you",
  "i'll hang you",
  "i'll torture you",
  "i'll finish you",
  "i'll erase you",
  "you're gonna die",
  "say goodbye to your life",
  "i hope you die",
  "i hope you choke",
  "i hope you suffer",
  "i hope you rot",
  "i hope you burn",
  "drop dead",
  "go die",
  "why don't you die",
  "wish you were dead",
  "i'll bury you",

  // Leetspeak/Obfuscated Threats (English)
  "1'll k1ll y0u",
  "1 w1ll k1ll y0u",
  "1'll st@b y0u",
  "1'll sh00t y0u",
  "1'll d3str0y y0u",
  "1'll h@rm y0u",
  "i w1ll punc# y0u",
  "1 w1ll ch0k3 y0u",
  "1'll r1p y0u @p@rt",
  "u'r3 d34d",
  "u w1ll di3",
  "1 h0p3 u di3",
  "g0 di3",
  "i'll k!ll y0u",
  "y0u'r3 g0nn@ di3",
  "y0u'r3 f***1ng d34d",
  "1'll m@k3 y0u suf3r",
  "1'll t0rtur3 y0u",

  // Leetspeak/Obfuscated Threats (Tagalog)
  "p@t@y1n k1t@",
  "s@ks@k1n k1t@",
  "put*lan k1t@",
  "b@r1l1n k1t@",
  "t1t1r@h1n k1t@",
  "b@tuk@ k1t@",
  "pup*kpuk1n k1t@",
  "s@s*ugur1n k1t@",

  // Tagalog/Filipino Misspellings/Leetspeak
  "p*t@y1n k1t@",
  "p@t@yn k1t@",
  "put@ng ina",
  "putang ina",
  "put*ng ina",
  "putangina",
  "p*tang ina",
  "p*tangina",
  "puta ka",
  "p*ta ka",
  "g@g*",
  "g@go",
  "t@ng ina",
  "tang ina",
  "tangina",
  "b0b0",
  "ul*l",
  "b@bob0",

  // More Leetspeak
  "s@ks@k1n",
  "b@r1l1n",
  "b@tuk@",
  "sund@ng0n",
  "b*n@l0n",
  "s@t0ng0n",
  "pup*kpuk1n",

  // Bisaya/Cebuano Misspellings/Leetspeak
  "patyon t1ka",
  "pamatyon t1ka",
  "sug@t@n t1ka",
  "bunalon t1ka",
  "tuk@on t1ka",
  "pat*y*n t1ka",
  "susuk0t t1ka",
  "sundang0n t1ka",

  // Hiligaynon/Ilonggo Misspellings/Leetspeak
  "paty0n ta ikaw",
  "p@t*yon ta ikaw",
  "sakit0n ta ikaw",
  "bagulb0l0n ta ikaw",
  "sug@t0n ta ikaw",

  // Waray Misspellings/Leetspeak
  "p@t@y0n ko ikaw",
  "p@t*yon ko ikaw",
  "sund@ng0n ko ikaw",
  "sug@t0n ko ikaw",

  // Chavacano Misspellings/Leetspeak
  "m@to yo contigo",
  "bunal y0 contigo",
  "p@t3 yo contigo",
  "apuy0 yo contigo",
];

function escapeRegExp(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export const hasThreat = (text) => {
  return THREAT_LIST.some((word) => {
    const safeWord = escapeRegExp(word);
    const flexibleSpaces = safeWord.replace(/\s+/g, "\\s*");
    const regex = new RegExp(`\\b${flexibleSpaces}\\b`, "i");
    return regex.test(text.toLowerCase());
  });
};

export const hasProfanity = (text) => {
  if (!text) return false;

  // Exact word matching (no leetspeak substitutions)
  return PROFANITY_LIST.some((word) => {
    const exactWordRegex = new RegExp(
      `(^|\\s)${word.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}(\\s|$)`,
      "i"
    );
    return exactWordRegex.test(text);
  });
};
